sudo: required
servcie: 
        - docker

before_install:
        - docker build -t kengang/react-test -f ./client/Dockerfile.dev ./client
script:
        - docker run kengang/reach-test npm test -- --converage

after_success:
        - docker build -t kengang/multi-client ./client
        - docker build -t kengang/multi-server ./server
        - docker build -t kengang/multi-nginx ./nginx
        - docker build -t kengang/multi-worker ./worker

        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push kengang/multi-client
        - docker push kengang/multi-server
        - docker push kengang/multi-nginx
        - docker push kengang/multi-worker

