sudo: required
service: 
        - docker

before_install:
        - docker build -t kengang/react-test -f ./client/Dockerfile.dev ./client
script:
        - docker run kengang/react-test npm test -- --coverage

after_success:
        - docker build -t kenmei/multi-client ./client
        - docker build -t kenmei/multi-server ./server
        - docker build -t kenmei/multi-nginx ./nginx
        - docker build -t kenmei/multi-worker ./worker

        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push kenmei/multi-client
        - docker push kenmei/multi-server
        - docker push kenmei/multi-nginx
        - docker push kenmei/multi-worker

